FROM openvino_base
RUN DEBIAN_FRONTEND="noninteractive"

USER root
RUN apt update
RUN apt-get -y install tzdata libopencv-dev virtualenvwrapper

RUN pip3 install ipython \
         pyyaml \
         opencv-python \
         torch=1.4 
        
RUN usermod -aG video openvino
# create user
USER openvino 
WORKDIR /home/openvino

